import ICardSet from '../../interfaces/ICardSet';

const analogBrainCards: ICardSet = {
  id: 'original_analog_brain',
  title: 'Original Analog Brain',
  lang: 'en',
  isDefaultForLanguage: true,
  cards: [
    {
      id: '0-1',
      title: 'Do you know what you want?',
      items: [
        { text: 'Yes', nextCardId: '0-2' },
        { text: 'No', nextCardId: '0-3' },
      ],
    },
    {
      id: '0-2',
      title: 'What do you want to do?',
      items: [
        { text: 'I’m bored and I want to do something', nextCardId: '2-1' },
        { text: 'I’m having emotions and need to deal with them', nextCardId: '1-1' },
        { text: 'I am procrastinating and want to stop', nextCardId: '1-12' },
        { text: 'I am in pain', nextCardId: '5-1' },
        { text: 'I want to sleep', nextCardId: '5-12' },
        { text: 'I want to clean', nextCardId: '4-2' },
        { text: 'I want to eat', nextCardId: '4-7' },
      ],
    },
    {
      id: '0-3',
      title: 'How are you feeling?',
      items: [
        { text: 'Overstimulated', nextCardId: '1-6' },
        { text: 'In pain', nextCardId: '5-1' },
        { text: 'Anxious', nextCardId: '1-2' },
        { text: 'Tired', nextCardId: '5-11' },
        { text: 'Self-critical / shame', nextCardId: '1-3' },
        { text: 'Angry', nextCardId: '1-4' },
        { text: 'Hungry', nextCardId: '4-7' },
        { text: 'Antsy', nextCardId: '3-1' },
        { text: 'Bored', nextCardId: '2-1' },
        { text: 'Procrastinating', nextCardId: '1-12' },
        { text: 'Useless', nextCardId: '4-1' },
        { text: 'Dissociated / Not all there', nextCardId: '1-6' },
      ],
    },
    {
      id: '1-1',
      title: 'I’m having emotions and need to deal with them:',
      items: [
        { text: 'Panic / anxiety', nextCardId: '1-2' },
        { text: 'Shame / self-critical', nextCardId: '1-3' },
        { text: 'Anger', nextCardId: '1-4' },
        { text: 'Understimulated / low', nextCardId: '1-14' },
        { text: 'All emotions: grounding exercise', nextCardId: '1-6' },
      ],
    },
    {
      id: '1-2',
      title: 'Dealing with a panic attack / anxiety',
      items: [
        { text: 'Take a xanax, ativan, benadryl, or other panic medication as directed' },
        { text: 'Listen to music' },
        { text: 'Drink a large glass of water' },
        { text: 'Quick exercises', nextCardId: '3-2' },
        { text: 'Grounding exercises', nextCardId: '1-6' },
        { text: 'Watch something comforting', nextCardId: '2-3' },
        { text: 'Do something creative', nextCardId: '2-4' },
        { text: 'Clean a thing', nextCardId: '4-2' },
        { text: 'Eat something', nextCardId: '4-7' },
        { text: 'Take a shower or bath' },
        { text: 'Call a hotline for help', nextCardId: '1-13' },
      ],
    },
    {
      id: '1-3',
      title: 'Dealing with shame / self-criticism',
      items: [
        { text: 'Make a list of your favorite things' },
        { text: 'Think of a time when you did well' },
        { text: 'List 18 things you’re grateful for' },
        { text: 'Reach out to a trusted person' },
        { text: 'Do a grounding exercise', nextCardId: '1-6' },
        { text: 'Deal with a panic attack', nextCardId: '1-2' },
        { text: 'Stop procrastinating something', nextCardId: '1-12' },
      ],
    },
    {
      id: '1-4',
      title: 'Dealing with anger',
      items: [
        {
          text: 'Step back from the current situation and check in with yourself and your body. Are you feeling anxious? In danger? In fight-or-flight?',
        },
        { text: 'Drink a glass of water' },
        { text: 'Eat something', nextCardId: '4-7' },
        { text: 'Focus on your breathing - breathe in a count of 4 and out a count of 8. Do this 10 times.' },
        { text: 'Do a grounding exercise', nextCardId: '1-6' },
        { text: 'Do a quick exercise', nextCardId: '3-2' },
        { text: 'Deal with a panic attack', nextCardId: '1-2' },
      ],
    },
    {
      id: '1-5',
      title: 'Overstimulation fixes',
      items: [
        { text: 'Listen to music' },
        { text: 'Earplugs' },
        { text: 'Noise canceling headphones' },
        { text: 'White noise' },
        { text: 'Take a shower' },
        { text: 'Brush your hair' },
        { text: 'Stand in the middle of a quiet room and breathe' },
        { text: 'Remove offending clothing item' },
        { text: 'Cough drop' },
        { text: 'Do cardio', nextCardId: '3-3' },
        { text: 'Do yoga', nextCardId: '3-4' },
        { text: 'Eat something', nextCardId: '4-7' },
        { text: 'Grounding exercise', nextCardId: '1-6' },
        { text: 'Sleep', nextCardId: '5-12' },
      ],
    },
    {
      id: '1-6',
      title: 'Grounding techniques',
      items: [
        { text: 'Mental grounding techniques', nextCardId: '1-7' },
        { text: 'Physical grounding techniques', nextCardId: '1-10' },
        { text: 'Soothing grounding techniques', nextCardId: '1-11' },
        { text: '“5-4-3-2-1” grounding exercise', nextCardId: '1-8' },
        { text: 'The airplane exercise', nextCardId: '1-9' },
      ],
    },
    {
      id: '1-7',
      title: 'Mental grounding techniques',
      items: [
        { text: 'Describe your environment out loud in detail, using all your senses' },
        { text: 'List all the items in a category (i.e., names of every tree)' },
        { text: 'Describe an everyday activity in great details (i.e. how to make coffee)' },
        { text: 'Read something out loud' },
        { text: 'Think of a word and spell it backwards' },
        { text: 'Count to 10 out loud' },
        { text: 'Say the alphabet very slowly' },
        { text: 'Repeat a favorite saying' },
        { text: 'Find something you can see for each color of the rainbow' },
        { text: '"5-4-3-2-1" exercise', nextCardId: '1-8' },
        { text: 'Do the airplane technique', nextCardId: '1-9' },
      ],
    },
    {
      id: '1-8',
      title: '"5-4-3-2-1" grounding exercise',
      items: [
        { text: '5 things you can see' },
        { text: '4 things you can touch or feel' },
        { text: '3 things you can hear' },
        { text: '2 things you can smell' },
        { text: '1 thing you can taste' },
      ],
    },
    {
      id: '1-9',
      title: 'Do the airplane exercise for panic',
      items: [
        {
          text: 'Imagine an airplane. This is your airplane and yours only. You get to decide what to do with it. For each of the following questions, say your answer out loud.',
        },
        { text: 'So what color will the outside be?' },
        { text: 'And the inside?' },
        { text: 'And the seats? Are they fluffy or normal? And what color?' },
        { text: 'Now 3 dishes to serve. An appetizer, a main dish, and a dessert' },
        {
          text: 'Who do you want to take on the plane with you? It can be up to 24 people, real or fictional',
        },
        { text: 'Are there any decorations on the plane?' },
        { text: 'What would the flight attendants look like?' },
        { text: 'Where is the plane going?' },
      ],
    },
    {
      id: '1-10',
      title: 'Physical grounding techniques',
      items: [
        { text: 'Splash cool water on your hands and face' },
        { text: 'Grab something as tightly as you can, then release. Repeat.' },
        { text: 'Touch objects around you and notice the sensory details' },
        { text: 'Dip your heels into the floor' },
        { text: 'Jump up and down' },
        { text: 'Notice your body, what each muscle is doing' },
        { text: 'Stretch' },
        { text: 'Walk slowly, noticing each footstep' },
        { text: 'Eat something and describe its flavors' },
        { text: 'Focus on your breathing - breathe in a count of 4 and out a count of 8.' },
      ],
    },
    {
      id: '1-11',
      title: 'Soothing grounding techniques',
      items: [
        { text: 'Say kind statements' },
        { text: 'Think of your favorite things, foods, people, animals' },
        { text: 'Picture people you care about' },
        { text: 'Remember the words to an inspiring song, quote, or poem' },
        { text: 'Remember a safe place' },
        { text: 'Say a coping statement' },
        { text: 'Plan out a safe treat for yourself' },
        { text: 'Think of things you are looking forward to in the next week' },
      ],
    },
    {
      id: '1-12',
      title: 'I am procrastinating and want to stop',
      items: [
        { text: 'Split the task into smaller tasks until each task seems less overwhelming' },
        { text: 'Find a way to start (even by making small progress)' },
        { text: 'Make it more interesting' },
        {
          text: "Stop and try to figure out if there is a mental block stopping you (eg you don't understand the task or you have a bad association with it or you're stuck on something specific)",
        },
      ],
    },
    {
      id: '1-13',
      title: 'Hotlines for more help',
      items: [
        { text: 'Australia and New Zealand:' },
        { text: 'Lifeline Australia: 13 11 14' },
        { text: 'Lifeline New Zealand: 09 5222 999 (Auckland), 0800 543 354 (Rest of NZ)' },
        { text: 'Canada:' },
        { text: 'Crisis Services Canada: 1-833-456-4566 toll free' },
        { text: 'In QC: 1-866-277-3553' },
        { text: 'France (English Speaking):' },
        { text: 'Suicide Ecoute: 0033 145 39 4000' },
        { text: 'SOS Help: 01 46 21 46 46' },
        { text: 'Germany:' },
        { text: 'Telefonseelsorge Deutschland (National):' },
        { text: 'German speaking: 0800 -111 0 222' },
        { text: 'English speaking: 030-44 01 06 07' },
        { text: 'Italy:' },
        { text: 'Samaritans: 800 86 00 22' },
        { text: 'Japan:' },
        { text: 'Befrienders International, Tokyo: +81 (0) 3 5286 9090' },
        { text: 'BI Suicide Prevention Centre, Osaka: +81 (0) 6 4395 4343' },
        { text: 'Tokyo English Lifeline: 107-0062' },
        { text: 'South Africa:' },
        { text: 'Lifeline Southern Africa: 0861 322 322' },
        { text: 'UK and Republic of Ireland:' },
        { text: 'Samaritans: 116 123' },
        { text: 'HopeLine UK: 0800 068 4141' },
        { text: 'Ireland Lifeline: 0808 808 8000' },
        { text: 'USA:' },
        { text: 'Suicide and Crisis Lifeline - call or text 988' },
        { text: 'The Trevor Project: 866-488-7386' },
        { text: 'Trans Lifeline at 877-565-8860' },
        { text: 'HopeLine 1-800-273-TALK (8255)' },
        { text: 'More international Suicide Hotlines available at suicide.org' },
      ],
    },
    {
      id: '1-14',
      title: 'Understimulation fixes',
      items: [
        { text: 'Physical activity', nextCardId: '3-1' },
        { text: 'Sunlight', nextCardId: '2-7' },
        { text: 'Food', nextCardId: '4-7' },
        { text: 'Sleep', nextCardId: '5-12' },
        { text: 'Personal time', nextCardId: '2-1' },
        { text: 'Creative expression', nextCardId: '2-4' },
      ],
    },
    {
      id: '2-1',
      title: 'I’m bored and I want to do something:',
      items: [
        { text: 'Get my body moving', nextCardId: '3-1' },
        { text: 'Read something', nextCardId: '2-2' },
        { text: 'Watch something', nextCardId: '2-3' },
        { text: 'Be creative', nextCardId: '2-4' },
        { text: 'Learn something', nextCardId: '2-5' },
        { text: 'Do something useful', nextCardId: '4-1' },
        { text: 'Have an adventure', nextCardId: '2-7' },
        { text: 'Play a game', nextCardId: '2-8' },
      ],
    },
    {
      id: '2-2',
      title: 'What do you want to read?',
      items: [
        { text: 'Fiction' },
        { text: 'Poetry' },
        { text: 'Nonfiction' },
        { text: 'YA fiction' },
        { text: 'Scifi' },
        { text: 'Fantasy' },
        { text: 'Mystery' },
        { text: 'Horror' },
        { text: 'Romance' },
        { text: 'Go to Project Gutenberg for legally free ebooks' },
        {
          text: 'Connect your library card to Libby for free eBooks and to Overdrive for free access to audiobooks',
        },
        { text: 'Fanfiction', link: 'http://archiveofourown.org' },
      ],
    },
    {
      id: '2-3',
      title: 'What do you want to watch?',
      items: [
        { text: 'Comfort movie' },
        { text: 'New movie' },
        { text: 'Comfort TV' },
        { text: 'New TV' },
        { text: 'Documentary' },
      ],
    },
    {
      id: '2-4',
      title: 'Creative things to do',
      items: [
        { text: 'Sew / Quilt' },
        { text: 'Crochet / Knit' },
        { text: 'Weave' },
        { text: 'Draw' },
        { text: 'Paint' },
        { text: 'Calligraphy' },
        { text: 'Write fiction' },
        { text: 'Write poetry' },
        { text: 'Origami' },
        { text: 'Embroider' },
        { text: 'Build something' },
      ],
    },
    {
      id: '2-5',
      title: 'Ways to learn things:',
      items: [
        { text: 'Learn a language', nextCardId: '2-6' },
        { text: 'Wikipedia', link: 'https://en.wikipedia.org' },
        { text: 'TedX Talks', link: 'https://www.ted.com/watch/tedx-talks' },
        { text: 'Explore the ocean with nautiluslive.org', link: 'http://nautiluslive.org' },
        { text: 'Pick the FIRST interesting-looking course you see on EdX' },
        { text: 'Watch a PBS documentary' },
        { text: 'Start reading the FIRST unread nonfiction book you see on your shelf' },
        { text: 'Read a random Wikipedia article', link: 'https://en.wikipedia.org/wiki/Special:Random' },
      ],
    },
    {
      id: '2-6',
      title: 'Learn a language',
      items: [
        { text: 'Drops', link: 'https://languagedrops.com/' },
        { text: 'Mango Languages (free with library card)', link: 'https://mangolanguages.com/' },
        { text: 'Duolingo', link: 'https://www.duolingo.com/' },
      ],
    },
    {
      id: '2-7',
      title: 'Have an adventure',
      items: [
        { text: 'Hiking' },
        { text: 'Birdwatching' },
        { text: 'Biking' },
        { text: 'State park / nature area' },
        { text: 'Museum' },
        { text: 'Botanical garden' },
        { text: 'Orchard' },
        { text: 'Science museum' },
        { text: 'Bookstore' },
        { text: 'Craft store' },
        { text: 'New restaurant' },
        { text: 'Zoo' },
        { text: 'Aquarium' },
      ],
    },
    {
      id: '2-8',
      title: 'Play a game',
      items: [
        { text: 'Card games' },
        { text: 'Board games' },
        { text: 'Video games' },
        { text: 'Phone games' },
      ],
    },
    {
      id: '3-1',
      title: 'What kind of exercise do you want to do?',
      items: [
        { text: 'Weight exercises you don’t need a gym to do', nextCardId: '3-2' },
        { text: 'Yoga', nextCardId: '3-4' },
        { text: 'Cardio you don’t need a gym to do', nextCardId: '3-3' },
      ],
    },
    {
      id: '3-2',
      title: 'Body weight exercises',
      items: [
        { text: 'Wall push-up' },
        { text: 'Chair Tricep dips' },
        { text: 'Squats' },
        { text: 'Lunges' },
        { text: 'Calf raises' },
        { text: 'Sit ups' },
      ],
    },
    {
      id: '3-3',
      title: 'Cardio exercises',
      items: [
        { text: 'Brisk walk' },
        { text: 'Run' },
        { text: 'Elliptical' },
        { text: 'Treadmill' },
        { text: 'Bike' },
        { text: 'Jumping jacks' },
        { text: 'Burpees' },
        { text: 'Jump rope' },
        { text: 'Dance' },
      ],
    },
    {
      id: '3-4',
      title: 'Yoga Resources',
      items: [
        { text: 'Yoga with Adriene YouTube channel', link: 'https://www.youtube.com/user/yogawithadriene' },
        { text: 'Jessamyn at The Underbelly', link: 'https://theunderbelly.com/' },
        { text: 'James Knight at Gentle Somatic Yoga', link: 'https://www.gentlesomaticyoga.com/' },
        { text: 'Dianne Bondy at Yoga for Every Body', link: 'https://diannebondyyoga.com/' },
        { text: 'Val Verdier', link: 'https://www.instagram.com/valerie.a.verdier/?hl=en' },
      ],
    },
    {
      id: '4-1',
      title: 'Useful things to do',
      items: [
        { text: 'Clean something', nextCardId: '4-2' },
        { text: 'Do homework' },
        { text: 'Check on your bank account / finances' },
        { text: 'Cook a meal' },
        { text: 'Organize a cupboard, shelf, closet, or other discrete space' },
        { text: 'Call a friend or relative to check on them' },
        { text: 'Sort the mail' },
        { text: 'Take out the garbage / recycling' },
      ],
    },
    {
      id: '4-2',
      title: 'Stuff to clean',
      items: [
        { text: 'Kitchen', nextCardId: '4-3' },
        { text: 'Bathroom', nextCardId: '4-4' },
        { text: 'Bedroom', nextCardId: '4-5' },
        { text: 'General living area', nextCardId: '4-6' },
      ],
    },
    {
      id: '4-3',
      title: 'Cleaning the Kitchen',
      items: [
        { text: 'Put away the clean dishes' },
        { text: 'Wash the dirty dishes' },
        { text: 'Wipe down the kitchen counters, stovetop' },
        { text: 'Sweep the kitchen floor' },
        { text: 'Wipe down the fridge shelves' },
        { text: 'Throw out old food' },
        { text: 'Empty the trash' },
        { text: 'Organize fridge and pantry' },
      ],
    },
    {
      id: '4-4',
      title: 'Cleaning the Bathroom',
      items: [
        { text: 'Detoxify the toilet with toilet brush + toilet cleaner' },
        { text: 'Empty the trash' },
        { text: 'Wash the bathroom mirror, counters, floor' },
        { text: 'Take down the shower curtain and run it through the wash' },
        { text: 'Scrub the mildew off the tub/shower stall' },
        { text: 'Put dirty laundry / towels in hamper' },
        { text: 'Organize counter / cabinet' },
        { text: 'Sweep/vacuum the floor' },
      ],
    },
    {
      id: '4-5',
      title: 'Cleaning the Bedroom',
      items: [
        { text: 'Change the sheets on the bed' },
        { text: 'Put the dirty sheets in the wash' },
        { text: 'Put the dirty laundry in the hamper' },
        { text: 'Empty the trash' },
        { text: 'Fold clean laundry' },
        { text: 'Put clean laundry away' },
        { text: 'Sweep / vacuum the floor' },
        { text: 'Wipe clean the tops of furniture' },
        { text: 'Organize nightstand / dresser' },
      ],
    },
    {
      id: '4-6',
      title: 'Cleaning general living area',
      items: [
        { text: 'Vacuum all visible rugs or carpets' },
        { text: 'Sweep or vacuum the floors' },
        { text: 'Pick up clutter and put it away' },
        { text: 'Walk around with a trash bag and throw out all rubbish' },
      ],
    },
    {
      id: '4-7',
      title: 'You need to eat. Where are you?',
      items: [
        { text: 'Home', nextCardId: '4-8' },
        { text: 'Work', nextCardId: '4-9' },
        { text: 'Grocery store', nextCardId: '4-10' },
        { text: 'Somewhere else', nextCardId: '4-11' },
      ],
    },
    {
      id: '4-8',
      title: "You want something to eat, and you're at home.",
      items: [
        { text: 'Spoonful of peanut butter' },
        { text: 'Slice of bread with jelly or butter' },
        { text: 'Scrambled egg' },
        { text: 'Oatmeal' },
        { text: 'Cereal' },
        { text: 'Crackers' },
        { text: 'Cheese' },
        { text: 'Chocolate milk' },
        { text: 'Raw veggies (carrots, broccoli, cucumber) with hummus or dressing' },
        {
          text: 'Microwave a bowl of frozen veggies with olive oil, salt, pepper, and other spices (paprika! cumin! thyme!)',
        },
        { text: 'Fruit' },
        { text: 'Peanuts, walnuts, other nuts or seeds' },
        { text: 'Glass of juice / smoothie' },
        { text: 'Packaged food (i.e. pop-tarts, microwave burritos)' },
        { text: '“Easy to stomach foods”: Banana, Rice, Applesauce, Toast, Yoghurt' },
      ],
    },
    {
      id: '4-9',
      title: "You're hungry and you're at work.",
      items: [
        { text: 'Hummus & crackers' },
        { text: 'Yogurt cup' },
        { text: 'Cheese stick' },
        { text: 'Bagel / english muffin / toast' },
        { text: 'Salad bar: greens, seeds, nuts, fruit, hard-boiled eggs' },
        { text: 'Soup bar' },
        { text: 'Granola bar' },
        { text: 'Peanut M&Ms' },
        { text: 'Trail mix' },
        {
          text: 'Anything with protein / fats / fiber will stick in your stomach longer than something with just sugar / flour.',
        },
        { text: 'Order delivery from DoorDash, Panera Bread, Local Pizza Place, etc (if available).' },
        { text: 'Check the break rooms for free food' },
        { text: 'Ask coworkers' },
      ],
    },
    {
      id: '4-10',
      title: "You’re hungry and you're at the grocery store.",
      items: [
        { text: 'Pre-made meals in the fresh foods section' },
        { text: 'Pre-washed, pre-packaged raw fruits / vegetables (produce section)' },
        { text: 'Lunchable (deli section)' },
        { text: 'Individually wrapped cheese (dairy aisle)' },
        { text: 'Yogurt cup (dairy aisle)' },
        {
          text: 'Baby food pouches (available in the baby aisle, no utensils needed, varieties include Banana & Pumpkin, Mango & Kale, Strawberry Banana.)',
        },
        { text: 'Pre-made smoothie (drinks aisle)' },
      ],
    },
    {
      id: '4-11',
      title: "You're hungry, and you're out and about.",
      items: [
        { text: 'Gas station (pre-made smoothie, cookies, nuts, packaged baked goods)' },
        {
          text: "Fast food (You don't have to order a full $8 meal. You can get just an order of fries, or a milkshake, or a 4-pack of chicken nuggets)",
        },
        { text: 'Grocery store', nextCardId: '4-10' },
        { text: 'Home', nextCardId: '4-8' },
      ],
    },
    {
      id: '5-1',
      title: 'What kind of pain are you having?',
      items: [
        { text: 'Menstrual / pelvic pain', nextCardId: '5-2' },
        { text: 'Joint pain', nextCardId: '5-3' },
        { text: 'Head', nextCardId: '5-5' },
        { text: 'Exercise-induced soreness', nextCardId: '5-4' },
        { text: 'Stomach', nextCardId: '5-10' },
      ],
    },
    {
      id: '5-2',
      title: 'How to deal with menstrual pain',
      items: [
        { text: 'Apply a heating pad' },
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'TENS unit' },
        { text: 'Exercise', nextCardId: '3-1' },
        { text: 'Drink water' },
        { text: 'Take a hot bath' },
        { text: 'Eat chocolate' },
        { text: 'Eat something salty' },
        { text: 'Distract yourself', nextCardId: '2-1' },
      ],
    },
    {
      id: '5-3',
      title: 'How to deal with joint/injury pain',
      items: [
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'Apply ice or heat (whichever feels good) for 20 minutes on, 20 minutes off, repeated' },
        { text: 'Massage' },
        { text: 'Foam roller' },
        { text: 'Warm bath' },
        { text: 'Choose a yoga video focused on that area', nextCardId: '3-4' },
      ],
    },
    {
      id: '5-4',
      title: 'How to deal with delayed-onset muscle soreness',
      items: [
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'Drink water' },
        { text: 'Stretching' },
        { text: 'Yoga', nextCardId: '3-4' },
        { text: 'Light cardio workout', nextCardId: '3-3' },
        { text: 'Warm bath' },
      ],
    },
    {
      id: '5-5',
      title: 'What kind of head pain?',
      items: [
        { text: 'Sinuses (when I press on my face it hurts worse)', nextCardId: '5-6' },
        {
          text: 'Tension (shoulders and neck hurt, or a rubber band is squeezing my skull)',
          nextCardId: '5-7',
        },
        {
          text: 'Migraine (light/sound/smell sensitivity, nausea, brain fog, emotions haywire)',
          nextCardId: '5-8',
        },
        { text: 'General headache', nextCardId: '5-9' },
      ],
    },
    {
      id: '5-6',
      title: 'How to deal with a sinus headache',
      items: [
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'Take a decongestant (Sudafed, Mucinex, etc)' },
        { text: 'Saline nasal spray' },
        { text: 'Shower' },
        { text: 'Drink water' },
        { text: 'Ice pack (wrapped in a towel) on your face' },
        { text: 'Pad your face with a towel and massage your face with a vibrator on the lowest setting' },
      ],
    },
    {
      id: '5-7',
      title: 'How to deal with a tension headache',
      items: [
        { text: 'Neck/back rub' },
        { text: 'Heating pad or ice pack (whichever feels good)' },
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'Muscle relaxant (if prescribed)' },
        { text: 'Take a hot shower' },
        { text: 'Cardio', nextCardId: '3-3' },
        { text: 'Unclench your jaw' },
        { text: 'Light exercise', nextCardId: '3-1' },
      ],
    },
    {
      id: '5-8',
      title: 'How to deal with a migraine (with aura)',
      items: [
        { text: 'Take your emergency migraine meds (if prescribed)' },
        { text: 'Drink a full glass of water' },
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs or other migraine meds.',
        },
        { text: 'Take 1,000mg of Magnesium Oxide' },
        { text: 'Take a benadryl and a nap' },
        { text: 'Eat something', nextCardId: '4-7' },
        { text: 'Put an ice pack or heat pad on your head, whichever feels better' },
        { text: 'Lay down in a dark, quiet room' },
        { text: 'Put in earplugs' },
        { text: 'Sleep', nextCardId: '5-12' },
        { text: 'Avoid bright lights / blue light devices' },
      ],
    },
    {
      id: '5-9',
      title: 'How to deal with a general headache',
      items: [
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'Eat something', nextCardId: '4-7' },
        { text: 'Drink a full glass of water' },
        { text: 'Rest if that feels comfortable' },
        { text: 'Light exercise if that feels comfortable' },
        { text: 'Reduce stimuli - sounds, lights, phone, humans' },
      ],
    },
    {
      id: '5-10',
      title: 'Stomach pain or nausea',
      items: [
        { text: 'Tums - if you have heartburn, sour stomach, or indigestion' },
        { text: 'Gas-X - if you feel gassy / bloated' },
        { text: 'Drink a glass of water' },
        { text: 'Toast/crackers/banana eaten in small bites' },
        { text: 'Ginger ale or ginger tea' },
        {
          text: 'If nauseous, lay on your left side (if comfortable). This puts your stomach below your esophagus and can reduce nausea / the urge to throw up.',
        },
      ],
    },
    {
      id: '5-11',
      title: 'When you’ve had bad sleep',
      items: [
        { text: 'Take a nap' },
        { text: 'Close your eyes, relax your body, and focus on your breathing for 3-5 minutes' },
        { text: 'Drink water' },
        { text: 'Take a warm bath' },
        { text: 'Prevent overstimulation', nextCardId: '1-5' },
        { text: 'Prevent a migraine', nextCardId: '5-5' },
        { text: 'Do a grounding exercise', nextCardId: '1-6' },
      ],
    },
    {
      id: '5-12',
      title: 'Improve sleep hygiene',
      items: [
        { text: 'I slept badly last night', nextCardId: '5-11' },
        { text: 'I have insomnia RIGHT NOW', nextCardId: '5-15' },
        { text: 'Fixing sleep in general', nextCardId: '5-13' },
        { text: 'I need to talk to a doctor about my sleep', nextCardId: '5-14' },
      ],
    },
    {
      id: '5-13',
      title: 'Tips to improve sleep hygiene',
      items: [
        {
          text: 'Set an alarm to start your nighttime routine at the same time every night, even if you aren’t tired when the alarm goes off. The point is to get all the Bedtime Tasks done and out of the way. Then the only task you have left is to close your eyes.',
        },
        {
          text: 'Try to get enough physical activity during the day. This can reduce how antsy you feel when you finally lay down.',
        },
        {
          text: 'Figure out how late you can consume caffeine without it affecting your bedtime, stick to that rule as much as you can. Knowing how caffeine affects you can help you control how it affects you.',
        },
        {
          text: 'Figure out how late you can take your ADHD meds or other stimulants without it affecting your bedtime. You may need to set an alarm to take your morning meds early enough.',
        },
        { text: 'Install a blue light filter for your phone / computer' },
        { text: 'Talk to your doctor about your sleep issues', nextCardId: '5-14' },
      ],
    },
    {
      id: '5-14',
      title: 'Sleep-related issues to ask your doctor about',
      items: [
        {
          text: 'Do you snore? Or breathe loudly at night? Ask your doctor about a sleep test for obstructive sleep apnea. Many apnea tests can be done at home overnight.',
        },
        {
          text: 'Do you fall asleep at random times / places? Many people with ADHD also have narcolepsy or another sleep disorder. Go over your symptoms with your doctor.',
        },
        { text: 'Do you get migraines?' },
        {
          text: 'Is it hard to fall asleep because your thoughts start spinning and your anxiety spikes? You may benefit from an anti-anxiety medication taken at bedtime to stop the spinning.',
        },
      ],
    },
    {
      id: '5-15',
      title: 'Dealing with insomnia',
      items: [
        { text: 'Turn off any bright lights' },
        { text: 'Use dark mode and blue light filter on your devices' },
        { text: 'Don’t watch exciting or mentally intense videos / movies / shows right before bed' },
        { text: 'Have a bedtime snack' },
        { text: 'Take melatonin or benadryl before bedtime' },
        { text: 'Take a hot shower. Your body will get more sleepy as it cools down.' },
        {
          text: 'Try a meditation app (such as the free, no-ads Mindfulness Coach app from the US Department of Veterans Affairs)',
        },
        { text: 'Listen to chill music, audio books or podcasts.' },
        {
          text: 'If nighttime noises bother you, try earplugs. Make sure your morning alarm is on the loudest setting and set to vibrate.',
        },
        {
          text: 'Put the phone down. Close your eyes. Breathe evenly and work on relaxing all your muscles, starting with your head and slowly working your way down.',
        },
        {
          text: 'Remember that even if you can’t sleep, just laying down with your eyes closed will give your mind and body some rest',
        },
      ],
    },
  ],
};

export default analogBrainCards;
