import ICardSet from '../interfaces/ICardSet';

export const analogBrainCards: ICardSet = {
  id: 'original_analog_brain',
  title: 'Analog Brain', // also used as id
  cards: [
    {
      id: '0-1',
      title: 'Do you know what you want?',
      items: [
        { text: 'Yes', nextCardId: '0-2' },
        { text: 'No', nextCardId: '0-3' },
      ],
    },
    {
      id: '0-2',
      title: 'What do you want to do?',
      items: [
        { text: 'I’m bored and I want to do something', nextCardId: '2-1' },
        { text: 'I’m having emotions and need to deal with them', nextCardId: '1-1' },
        { text: 'I am procrastinating and want to stop', nextCardId: '1-12' },
        { text: 'I am in pain', nextCardId: '5-1' },
        { text: 'I want to sleep', nextCardId: '5-12' },
        { text: 'I want to clean', nextCardId: '4-2' },
        { text: 'I want to eat', nextCardId: '4-7' },
      ],
    },
    {
      id: '0-3',
      title: 'How are you feeling?',
      items: [
        { text: 'Overstimulated', nextCardId: '1-6' },
        { text: 'In pain', nextCardId: '5-1' },
        { text: 'Anxious', nextCardId: '1-2' },
        { text: 'Tired', nextCardId: '5-11' },
        { text: 'Self-critical / shame', nextCardId: '1-3' },
        { text: 'Angry', nextCardId: '1-4' },
        { text: 'Hungry', nextCardId: '4-7' },
        { text: 'Antsy', nextCardId: '3-1' },
        { text: 'Bored', nextCardId: '2-1' },
        { text: 'Procrastinating', nextCardId: '1-12' },
        { text: 'Useless', nextCardId: '4-1' },
        { text: 'Dissociated / Not all there', nextCardId: '1-6' },
      ],
    },
    {
      id: '1-1',
      title: 'I’m having emotions and need to deal with them:',
      items: [
        { text: 'Panic / anxiety', nextCardId: '1-2' },
        { text: 'Shame / self-critical', nextCardId: '1-3' },
        { text: 'Anger', nextCardId: '1-4' },
        { text: 'Understimulated / low', nextCardId: '1-14' },
        { text: 'All emotions: grounding exercise', nextCardId: '1-6' },
      ],
    },
    {
      id: '1-2',
      title: 'Dealing with a panic attack / anxiety',
      items: [
        { text: 'Take a xanax, ativan, benadryl, or other panic medication as directed' },
        { text: 'Listen to music' },
        { text: 'Drink a large glass of water' },
        { text: 'Quick exercises', nextCardId: '3-2' },
        { text: 'Grounding exercises', nextCardId: '1-6' },
        { text: 'Watch something comforting', nextCardId: '2-3' },
        { text: 'Do something creative', nextCardId: '2-4' },
        { text: 'Clean a thing', nextCardId: '4-2' },
        { text: 'Eat something', nextCardId: '4-7' },
        { text: 'Take a shower or bath' },
        { text: 'Call a hotline for help', nextCardId: '1-13' },
      ],
    },
    {
      id: '1-3',
      title: 'Dealing with shame / self-criticism',
      items: [
        { text: 'Make a list of your favorite things' },
        { text: 'Think of a time when you did well' },
        { text: 'List 18 things you’re grateful for' },
        { text: 'Reach out to a trusted person' },
        { text: 'Do a grounding exercise', nextCardId: '1-6' },
        { text: 'Deal with a panic attack', nextCardId: '1-2' },
        { text: 'Stop procrastinating something', nextCardId: '1-12' },
      ],
    },
    {
      id: '1-4',
      title: 'Dealing with anger',
      items: [
        {
          text: 'Step back from the current situation and check in with yourself and your body. Are you feeling anxious? In danger? In fight-or-flight?',
        },
        { text: 'Drink a glass of water' },
        { text: 'Eat something', nextCardId: '4-7' },
        { text: 'Focus on your breathing - breathe in a count of 4 and out a count of 8. Do this 10 times.' },
        { text: 'Do a grounding exercise', nextCardId: '1-6' },
        { text: 'Do a quick exercise', nextCardId: '3-2' },
        { text: 'Deal with a panic attack', nextCardId: '1-2' },
      ],
    },
    {
      id: '1-5',
      title: 'Overstimulation fixes',
      items: [
        { text: 'Listen to music' },
        { text: 'Earplugs' },
        { text: 'Noise canceling headphones' },
        { text: 'White noise' },
        { text: 'Take a shower' },
        { text: 'Brush your hair' },
        { text: 'Stand in the middle of a quiet room and breathe' },
        { text: 'Remove offending clothing item' },
        { text: 'Cough drop' },
        { text: 'Do cardio', nextCardId: '3-3' },
        { text: 'Do yoga', nextCardId: '3-4' },
        { text: 'Eat something', nextCardId: '4-7' },
        { text: 'Grounding exercise', nextCardId: '1-6' },
        { text: 'Sleep', nextCardId: '5-12' },
      ],
    },
    {
      id: '1-6',
      title: 'Grounding techniques',
      items: [
        { text: 'Mental grounding techniques', nextCardId: '1-7' },
        { text: 'Physical grounding techniques', nextCardId: '1-10' },
        { text: 'Soothing grounding techniques', nextCardId: '1-11' },
        { text: '“5-4-3-2-1” grounding exercise', nextCardId: '1-8' },
        { text: 'The airplane exercise', nextCardId: '1-9' },
      ],
    },
    {
      id: '1-7',
      title: 'Mental grounding techniques',
      items: [
        { text: 'Describe your environment out loud in detail, using all your senses' },
        { text: 'List all the items in a category (i.e., names of every tree)' },
        { text: 'Describe an everyday activity in great details (i.e. how to make coffee)' },
        { text: 'Read something out loud' },
        { text: 'Think of a word and spell it backwards' },
        { text: 'Count to 10 out loud' },
        { text: 'Say the alphabet very slowly' },
        { text: 'Repeat a favorite saying' },
        { text: 'Find something you can see for each color of the rainbow' },
        { text: '"5-4-3-2-1" exercise', nextCardId: '1-8' },
        { text: 'Do the airplane technique', nextCardId: '1-9' },
      ],
    },
    {
      id: '1-8',
      title: '"5-4-3-2-1" grounding exercise',
      items: [
        { text: '5 things you can see' },
        { text: '4 things you can touch or feel' },
        { text: '3 things you can hear' },
        { text: '2 things you can smell' },
        { text: '1 thing you can taste' },
      ],
    },
    {
      id: '1-9',
      title: 'Do the airplane exercise for panic',
      items: [
        {
          text: 'Imagine an airplane. This is your airplane and yours only. You get to decide what to do with it. For each of the following questions, say your answer out loud.',
        },
        { text: 'So what color will the outside be?' },
        { text: 'And the inside?' },
        { text: 'And the seats? Are they fluffy or normal? And what color?' },
        { text: 'Now 3 dishes to serve. An appetizer, a main dish, and a dessert' },
        {
          text: 'Who do you want to take on the plane with you? It can be up to 24 people, real or fictional',
        },
        { text: 'Are there any decorations on the plane?' },
        { text: 'What would the flight attendants look like?' },
        { text: 'Where is the plane going?' },
      ],
    },
    {
      id: '1-10',
      title: 'Physical grounding techniques',
      items: [
        { text: 'Splash cool water on your hands and face' },
        { text: 'Grab something as tightly as you can, then release. Repeat.' },
        { text: 'Touch objects around you and notice the sensory details' },
        { text: 'Dip your heels into the floor' },
        { text: 'Jump up and down' },
        { text: 'Notice your body, what each muscle is doing' },
        { text: 'Stretch' },
        { text: 'Walk slowly, noticing each footstep' },
        { text: 'Eat something and describe its flavors' },
        { text: 'Focus on your breathing - breathe in a count of 4 and out a count of 8.' },
      ],
    },
    {
      id: '1-11',
      title: 'Soothing grounding techniques',
      items: [
        { text: 'Say kind statements' },
        { text: 'Think of your favorite things, foods, people, animals' },
        { text: 'Picture people you care about' },
        { text: 'Remember the words to an inspiring song, quote, or poem' },
        { text: 'Remember a safe place' },
        { text: 'Say a coping statement' },
        { text: 'Plan out a safe treat for yourself' },
        { text: 'Think of things you are looking forward to in the next week' },
      ],
    },
    {
      id: '1-12',
      title: 'I am procrastinating and want to stop',
      items: [
        { text: 'Split the task into smaller tasks until each task seems less overwhelming' },
        { text: 'Find a way to start (even by making small progress)' },
        { text: 'Make it more interesting' },
        {
          text: "Stop and try to figure out if there is a mental block stopping you (eg you don't understand the task or you have a bad association with it or you're stuck on something specific)",
        },
      ],
    },
    {
      id: '1-13',
      title: 'Hotlines for more help',
      items: [
        { text: 'Australia and New Zealand:' },
        { text: 'Lifeline Australia: 13 11 14' },
        { text: 'Lifeline New Zealand: 09 5222 999 (Auckland), 0800 543 354 (Rest of NZ)' },
        { text: 'Canada:' },
        { text: 'Crisis Services Canada: 1-833-456-4566 toll free' },
        { text: 'In QC: 1-866-277-3553' },
        { text: 'France (English Speaking):' },
        { text: 'Suicide Ecoute: 0033 145 39 4000' },
        { text: 'SOS Help: 01 46 21 46 46' },
        { text: 'Germany:' },
        { text: 'Telefonseelsorge Deutschland (National):' },
        { text: 'German speaking: 0800 -111 0 222' },
        { text: 'English speaking: 030-44 01 06 07' },
        { text: 'Italy:' },
        { text: 'Samaritans: 800 86 00 22' },
        { text: 'Japan:' },
        { text: 'Befrienders International, Tokyo: +81 (0) 3 5286 9090' },
        { text: 'BI Suicide Prevention Centre, Osaka: +81 (0) 6 4395 4343' },
        { text: 'Tokyo English Lifeline: 107-0062' },
        { text: 'South Africa:' },
        { text: 'Lifeline Southern Africa: 0861 322 322' },
        { text: 'UK and Republic of Ireland:' },
        { text: 'Samaritans: 116 123' },
        { text: 'HopeLine UK: 0800 068 4141' },
        { text: 'Ireland Lifeline: 0808 808 8000' },
        { text: 'USA:' },
        { text: 'Suicide and Crisis Lifeline - call or text 988' },
        { text: 'The Trevor Project: 866-488-7386' },
        { text: 'Trans Lifeline at 877-565-8860' },
        { text: 'HopeLine 1-800-273-TALK (8255)' },
        { text: 'More international Suicide Hotlines available at suicide.org' },
      ],
    },
    {
      id: '1-14',
      title: 'Understimulation fixes',
      items: [
        { text: 'Physical activity', nextCardId: '3-1' },
        { text: 'Sunlight', nextCardId: '2-7' },
        { text: 'Food', nextCardId: '4-7' },
        { text: 'Sleep', nextCardId: '5-12' },
        { text: 'Personal time', nextCardId: '2-1' },
        { text: 'Creative expression', nextCardId: '2-4' },
      ],
    },
    {
      id: '2-1',
      title: 'I’m bored and I want to do something:',
      items: [
        { text: 'Get my body moving', nextCardId: '3-1' },
        { text: 'Read something', nextCardId: '2-2' },
        { text: 'Watch something', nextCardId: '2-3' },
        { text: 'Be creative', nextCardId: '2-4' },
        { text: 'Learn something', nextCardId: '2-5' },
        { text: 'Do something useful', nextCardId: '4-1' },
        { text: 'Have an adventure', nextCardId: '2-7' },
        { text: 'Play a game', nextCardId: '2-8' },
      ],
    },
    {
      id: '2-2',
      title: 'What do you want to read?',
      items: [
        { text: 'Fiction' },
        { text: 'Poetry' },
        { text: 'Nonfiction' },
        { text: 'YA fiction' },
        { text: 'Scifi' },
        { text: 'Fantasy' },
        { text: 'Mystery' },
        { text: 'Horror' },
        { text: 'Romance' },
        { text: 'Go to Project Gutenberg for legally free ebooks' },
        {
          text: 'Connect your library card to Libby for free eBooks and to Overdrive for free access to audiobooks',
        },
        { text: 'Fanfiction', link: 'http://archiveofourown.org' },
      ],
    },
    {
      id: '2-3',
      title: 'What do you want to watch?',
      items: [
        { text: 'Comfort movie' },
        { text: 'New movie' },
        { text: 'Comfort TV' },
        { text: 'New TV' },
        { text: 'Documentary' },
      ],
    },
    {
      id: '2-4',
      title: 'Creative things to do',
      items: [
        { text: 'Sew / Quilt' },
        { text: 'Crochet / Knit' },
        { text: 'Weave' },
        { text: 'Draw' },
        { text: 'Paint' },
        { text: 'Calligraphy' },
        { text: 'Write fiction' },
        { text: 'Write poetry' },
        { text: 'Origami' },
        { text: 'Embroider' },
        { text: 'Build something' },
      ],
    },
    {
      id: '2-5',
      title: 'Ways to learn things:',
      items: [
        { text: 'Learn a language', nextCardId: '2-6' },
        { text: 'Wikipedia', link: 'https://en.wikipedia.org' },
        { text: 'TedX Talks', link: 'https://www.ted.com/watch/tedx-talks' },
        { text: 'Explore the ocean with nautiluslive.org', link: 'http://nautiluslive.org' },
        { text: 'Pick the FIRST interesting-looking course you see on EdX' },
        { text: 'Watch a PBS documentary' },
        { text: 'Start reading the FIRST unread nonfiction book you see on your shelf' },
        { text: 'Read a random Wikipedia article', link: 'https://en.wikipedia.org/wiki/Special:Random' },
      ],
    },
    {
      id: '2-6',
      title: 'Learn a language',
      items: [
        { text: 'Drops', link: 'https://languagedrops.com/' },
        { text: 'Mango Languages (free with library card)', link: 'https://mangolanguages.com/' },
        { text: 'Duolingo', link: 'https://www.duolingo.com/' },
      ],
    },
    {
      id: '2-7',
      title: 'Have an adventure',
      items: [
        { text: 'Hiking' },
        { text: 'Birdwatching' },
        { text: 'Biking' },
        { text: 'State park / nature area' },
        { text: 'Museum' },
        { text: 'Botanical garden' },
        { text: 'Orchard' },
        { text: 'Science museum' },
        { text: 'Bookstore' },
        { text: 'Craft store' },
        { text: 'New restaurant' },
        { text: 'Zoo' },
        { text: 'Aquarium' },
      ],
    },
    {
      id: '2-8',
      title: 'Play a game',
      items: [
        { text: 'Card games' },
        { text: 'Board games' },
        { text: 'Video games' },
        { text: 'Phone games' },
      ],
    },
    {
      id: '3-1',
      title: 'What kind of exercise do you want to do?',
      items: [
        { text: 'Weight exercises you don’t need a gym to do', nextCardId: '3-2' },
        { text: 'Yoga', nextCardId: '3-4' },
        { text: 'Cardio you don’t need a gym to do', nextCardId: '3-3' },
      ],
    },
    {
      id: '3-2',
      title: 'Body weight exercises',
      items: [
        { text: 'Wall push-up' },
        { text: 'Chair Tricep dips' },
        { text: 'Squats' },
        { text: 'Lunges' },
        { text: 'Calf raises' },
        { text: 'Sit ups' },
      ],
    },
    {
      id: '3-3',
      title: 'Cardio exercises',
      items: [
        { text: 'Brisk walk' },
        { text: 'Run' },
        { text: 'Elliptical' },
        { text: 'Treadmill' },
        { text: 'Bike' },
        { text: 'Jumping jacks' },
        { text: 'Burpees' },
        { text: 'Jump rope' },
        { text: 'Dance' },
      ],
    },
    {
      id: '3-4',
      title: 'Yoga Resources',
      items: [
        { text: 'Yoga with Adriene YouTube channel', link: 'https://www.youtube.com/user/yogawithadriene' },
        { text: 'Jessamyn at The Underbelly', link: 'https://theunderbelly.com/' },
        { text: 'James Knight at Gentle Somatic Yoga', link: 'https://www.gentlesomaticyoga.com/' },
        { text: 'Dianne Bondy at Yoga for Every Body', link: 'https://diannebondyyoga.com/' },
        { text: 'Val Verdier', link: 'https://www.instagram.com/valerie.a.verdier/?hl=en' },
      ],
    },
    {
      id: '4-1',
      title: 'Useful things to do',
      items: [
        { text: 'Clean something', nextCardId: '4-2' },
        { text: 'Do homework' },
        { text: 'Check on your bank account / finances' },
        { text: 'Cook a meal' },
        { text: 'Organize a cupboard, shelf, closet, or other discrete space' },
        { text: 'Call a friend or relative to check on them' },
        { text: 'Sort the mail' },
        { text: 'Take out the garbage / recycling' },
      ],
    },
    {
      id: '4-2',
      title: 'Stuff to clean',
      items: [
        { text: 'Kitchen', nextCardId: '4-3' },
        { text: 'Bathroom', nextCardId: '4-4' },
        { text: 'Bedroom', nextCardId: '4-5' },
        { text: 'General living area', nextCardId: '4-6' },
      ],
    },
    {
      id: '4-3',
      title: 'Cleaning the Kitchen',
      items: [
        { text: 'Put away the clean dishes' },
        { text: 'Wash the dirty dishes' },
        { text: 'Wipe down the kitchen counters, stovetop' },
        { text: 'Sweep the kitchen floor' },
        { text: 'Wipe down the fridge shelves' },
        { text: 'Throw out old food' },
        { text: 'Empty the trash' },
        { text: 'Organize fridge and pantry' },
      ],
    },
    {
      id: '4-4',
      title: 'Cleaning the Bathroom',
      items: [
        { text: 'Detoxify the toilet with toilet brush + toilet cleaner' },
        { text: 'Empty the trash' },
        { text: 'Wash the bathroom mirror, counters, floor' },
        { text: 'Take down the shower curtain and run it through the wash' },
        { text: 'Scrub the mildew off the tub/shower stall' },
        { text: 'Put dirty laundry / towels in hamper' },
        { text: 'Organize counter / cabinet' },
        { text: 'Sweep/vacuum the floor' },
      ],
    },
    {
      id: '4-5',
      title: 'Cleaning the Bedroom',
      items: [
        { text: 'Change the sheets on the bed' },
        { text: 'Put the dirty sheets in the wash' },
        { text: 'Put the dirty laundry in the hamper' },
        { text: 'Empty the trash' },
        { text: 'Fold clean laundry' },
        { text: 'Put clean laundry away' },
        { text: 'Sweep / vacuum the floor' },
        { text: 'Wipe clean the tops of furniture' },
        { text: 'Organize nightstand / dresser' },
      ],
    },
    {
      id: '4-6',
      title: 'Cleaning general living area',
      items: [
        { text: 'Vacuum all visible rugs or carpets' },
        { text: 'Sweep or vacuum the floors' },
        { text: 'Pick up clutter and put it away' },
        { text: 'Walk around with a trash bag and throw out all rubbish' },
      ],
    },
    {
      id: '4-7',
      title: 'You need to eat. Where are you?',
      items: [
        { text: 'Home', nextCardId: '4-8' },
        { text: 'Work', nextCardId: '4-9' },
        { text: 'Grocery store', nextCardId: '4-10' },
        { text: 'Somewhere else', nextCardId: '4-11' },
      ],
    },
    {
      id: '4-8',
      title: "You want something to eat, and you're at home.",
      items: [
        { text: 'Spoonful of peanut butter' },
        { text: 'Slice of bread with jelly or butter' },
        { text: 'Scrambled egg' },
        { text: 'Oatmeal' },
        { text: 'Cereal' },
        { text: 'Crackers' },
        { text: 'Cheese' },
        { text: 'Chocolate milk' },
        { text: 'Raw veggies (carrots, broccoli, cucumber) with hummus or dressing' },
        {
          text: 'Microwave a bowl of frozen veggies with olive oil, salt, pepper, and other spices (paprika! cumin! thyme!)',
        },
        { text: 'Fruit' },
        { text: 'Peanuts, walnuts, other nuts or seeds' },
        { text: 'Glass of juice / smoothie' },
        { text: 'Packaged food (i.e. pop-tarts, microwave burritos)' },
        { text: '“Easy to stomach foods”: Banana, Rice, Applesauce, Toast, Yoghurt' },
      ],
    },
    {
      id: '4-9',
      title: "You're hungry and you're at work.",
      items: [
        { text: 'Hummus & crackers' },
        { text: 'Yogurt cup' },
        { text: 'Cheese stick' },
        { text: 'Bagel / english muffin / toast' },
        { text: 'Salad bar: greens, seeds, nuts, fruit, hard-boiled eggs' },
        { text: 'Soup bar' },
        { text: 'Granola bar' },
        { text: 'Peanut M&Ms' },
        { text: 'Trail mix' },
        {
          text: 'Anything with protein / fats / fiber will stick in your stomach longer than something with just sugar / flour.',
        },
        { text: 'Order delivery from DoorDash, Panera Bread, Local Pizza Place, etc (if available).' },
        { text: 'Check the break rooms for free food' },
        { text: 'Ask coworkers' },
      ],
    },
    {
      id: '4-10',
      title: "You’re hungry and you're at the grocery store.",
      items: [
        { text: 'Pre-made meals in the fresh foods section' },
        { text: 'Pre-washed, pre-packaged raw fruits / vegetables (produce section)' },
        { text: 'Lunchable (deli section)' },
        { text: 'Individually wrapped cheese (dairy aisle)' },
        { text: 'Yogurt cup (dairy aisle)' },
        {
          text: 'Baby food pouches (available in the baby aisle, no utensils needed, varieties include Banana & Pumpkin, Mango & Kale, Strawberry Banana.)',
        },
        { text: 'Pre-made smoothie (drinks aisle)' },
      ],
    },
    {
      id: '4-11',
      title: "You're hungry, and you're out and about.",
      items: [
        { text: 'Gas station (pre-made smoothie, cookies, nuts, packaged baked goods)' },
        {
          text: "Fast food (You don't have to order a full $8 meal. You can get just an order of fries, or a milkshake, or a 4-pack of chicken nuggets)",
        },
        { text: 'Grocery store', nextCardId: '4-10' },
        { text: 'Home', nextCardId: '4-8' },
      ],
    },
    {
      id: '5-1',
      title: 'What kind of pain are you having?',
      items: [
        { text: 'Menstrual / pelvic pain', nextCardId: '5-2' },
        { text: 'Joint pain', nextCardId: '5-3' },
        { text: 'Head', nextCardId: '5-5' },
        { text: 'Exercise-induced soreness', nextCardId: '5-4' },
        { text: 'Stomach', nextCardId: '5-10' },
      ],
    },
    {
      id: '5-2',
      title: 'How to deal with menstrual pain',
      items: [
        { text: 'Apply a heating pad' },
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'TENS unit' },
        { text: 'Exercise', nextCardId: '3-1' },
        { text: 'Drink water' },
        { text: 'Take a hot bath' },
        { text: 'Eat chocolate' },
        { text: 'Eat something salty' },
        { text: 'Distract yourself', nextCardId: '2-1' },
      ],
    },
    {
      id: '5-3',
      title: 'How to deal with joint/injury pain',
      items: [
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'Apply ice or heat (whichever feels good) for 20 minutes on, 20 minutes off, repeated' },
        { text: 'Massage' },
        { text: 'Foam roller' },
        { text: 'Warm bath' },
        { text: 'Choose a yoga video focused on that area', nextCardId: '3-4' },
      ],
    },
    {
      id: '5-4',
      title: 'How to deal with delayed-onset muscle soreness',
      items: [
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'Drink water' },
        { text: 'Stretching' },
        { text: 'Yoga', nextCardId: '3-4' },
        { text: 'Light cardio workout', nextCardId: '3-3' },
        { text: 'Warm bath' },
      ],
    },
    {
      id: '5-5',
      title: 'What kind of head pain?',
      items: [
        { text: 'Sinuses (when I press on my face it hurts worse)', nextCardId: '5-6' },
        {
          text: 'Tension (shoulders and neck hurt, or a rubber band is squeezing my skull)',
          nextCardId: '5-7',
        },
        {
          text: 'Migraine (light/sound/smell sensitivity, nausea, brain fog, emotions haywire)',
          nextCardId: '5-8',
        },
        { text: 'General headache', nextCardId: '5-9' },
      ],
    },
    {
      id: '5-6',
      title: 'How to deal with a sinus headache',
      items: [
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'Take a decongestant (Sudafed, Mucinex, etc)' },
        { text: 'Saline nasal spray' },
        { text: 'Shower' },
        { text: 'Drink water' },
        { text: 'Ice pack (wrapped in a towel) on your face' },
        { text: 'Pad your face with a towel and massage your face with a vibrator on the lowest setting' },
      ],
    },
    {
      id: '5-7',
      title: 'How to deal with a tension headache',
      items: [
        { text: 'Neck/back rub' },
        { text: 'Heating pad or ice pack (whichever feels good)' },
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'Muscle relaxant (if prescribed)' },
        { text: 'Take a hot shower' },
        { text: 'Cardio', nextCardId: '3-3' },
        { text: 'Unclench your jaw' },
        { text: 'Light exercise', nextCardId: '3-1' },
      ],
    },
    {
      id: '5-8',
      title: 'How to deal with a migraine (with aura)',
      items: [
        { text: 'Take your emergency migraine meds (if prescribed)' },
        { text: 'Drink a full glass of water' },
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs or other migraine meds.',
        },
        { text: 'Take 1,000mg of Magnesium Oxide' },
        { text: 'Take a benadryl and a nap' },
        { text: 'Eat something', nextCardId: '4-7' },
        { text: 'Put an ice pack or heat pad on your head, whichever feels better' },
        { text: 'Lay down in a dark, quiet room' },
        { text: 'Put in earplugs' },
        { text: 'Sleep', nextCardId: '5-12' },
        { text: 'Avoid bright lights / blue light devices' },
      ],
    },
    {
      id: '5-9',
      title: 'How to deal with a general headache',
      items: [
        {
          text: 'Take an NSAID pain reliever (e.g., Ibuprofen, Motrin, Advil, Aleve). Take with a full glass of water to prevent heartburn. Do not drink alcohol while taking NSAIDs.',
        },
        { text: 'Eat something', nextCardId: '4-7' },
        { text: 'Drink a full glass of water' },
        { text: 'Rest if that feels comfortable' },
        { text: 'Light exercise if that feels comfortable' },
        { text: 'Reduce stimuli - sounds, lights, phone, humans' },
      ],
    },
    {
      id: '5-10',
      title: 'Stomach pain or nausea',
      items: [
        { text: 'Tums - if you have heartburn, sour stomach, or indigestion' },
        { text: 'Gas-X - if you feel gassy / bloated' },
        { text: 'Drink a glass of water' },
        { text: 'Toast/crackers/banana eaten in small bites' },
        { text: 'Ginger ale or ginger tea' },
        {
          text: 'If nauseous, lay on your left side (if comfortable). This puts your stomach below your esophagus and can reduce nausea / the urge to throw up.',
        },
      ],
    },
    {
      id: '5-11',
      title: 'When you’ve had bad sleep',
      items: [
        { text: 'Take a nap' },
        { text: 'Close your eyes, relax your body, and focus on your breathing for 3-5 minutes' },
        { text: 'Drink water' },
        { text: 'Take a warm bath' },
        { text: 'Prevent overstimulation', nextCardId: '1-5' },
        { text: 'Prevent a migraine', nextCardId: '5-5' },
        { text: 'Do a grounding exercise', nextCardId: '1-6' },
      ],
    },
    {
      id: '5-12',
      title: 'Improve sleep hygiene',
      items: [
        { text: 'I slept badly last night', nextCardId: '5-11' },
        { text: 'I have insomnia RIGHT NOW', nextCardId: '5-15' },
        { text: 'Fixing sleep in general', nextCardId: '5-13' },
        { text: 'I need to talk to a doctor about my sleep', nextCardId: '5-14' },
      ],
    },
    {
      id: '5-13',
      title: 'Tips to improve sleep hygiene',
      items: [
        {
          text: 'Set an alarm to start your nighttime routine at the same time every night, even if you aren’t tired when the alarm goes off. The point is to get all the Bedtime Tasks done and out of the way. Then the only task you have left is to close your eyes.',
        },
        {
          text: 'Try to get enough physical activity during the day. This can reduce how antsy you feel when you finally lay down.',
        },
        {
          text: 'Figure out how late you can consume caffeine without it affecting your bedtime, stick to that rule as much as you can. Knowing how caffeine affects you can help you control how it affects you.',
        },
        {
          text: 'Figure out how late you can take your ADHD meds or other stimulants without it affecting your bedtime. You may need to set an alarm to take your morning meds early enough.',
        },
        { text: 'Install a blue light filter for your phone / computer' },
        { text: 'Talk to your doctor about your sleep issues', nextCardId: '5-14' },
      ],
    },
    {
      id: '5-14',
      title: 'Sleep-related issues to ask your doctor about',
      items: [
        {
          text: 'Do you snore? Or breathe loudly at night? Ask your doctor about a sleep test for obstructive sleep apnea. Many apnea tests can be done at home overnight.',
        },
        {
          text: 'Do you fall asleep at random times / places? Many people with ADHD also have narcolepsy or another sleep disorder. Go over your symptoms with your doctor.',
        },
        { text: 'Do you get migraines?' },
        {
          text: 'Is it hard to fall asleep because your thoughts start spinning and your anxiety spikes? You may benefit from an anti-anxiety medication taken at bedtime to stop the spinning.',
        },
      ],
    },
    {
      id: '5-15',
      title: 'Dealing with insomnia',
      items: [
        { text: 'Turn off any bright lights' },
        { text: 'Use dark mode and blue light filter on your devices' },
        { text: 'Don’t watch exciting or mentally intense videos / movies / shows right before bed' },
        { text: 'Have a bedtime snack' },
        { text: 'Take melatonin or benadryl before bedtime' },
        { text: 'Take a hot shower. Your body will get more sleepy as it cools down.' },
        {
          text: 'Try a meditation app (such as the free, no-ads Mindfulness Coach app from the US Department of Veterans Affairs)',
        },
        { text: 'Listen to chill music, audio books or podcasts.' },
        {
          text: 'If nighttime noises bother you, try earplugs. Make sure your morning alarm is on the loudest setting and set to vibrate.',
        },
        {
          text: 'Put the phone down. Close your eyes. Breathe evenly and work on relaxing all your muscles, starting with your head and slowly working your way down.',
        },
        {
          text: 'Remember that even if you can’t sleep, just laying down with your eyes closed will give your mind and body some rest',
        },
      ],
    },
  ],
};

export const analogBrainCardsFrench: ICardSet = {
  id: 'original_analog_brain_fr',
  title: 'Analog Brain (Français)',
  cards: [
    {
      id: '0-1',
      title: 'Savez-vous ce que vous voulez ?',
      items: [
        { text: 'Oui', nextCardId: '0-2' },
        { text: 'Non', nextCardId: '0-3' },
      ],
    },
    {
      id: '0-2',
      title: 'Que voulez-vous faire ?',
      items: [
        { text: 'Je m’ennuie et je veux faire quelque chose', nextCardId: '2-1' },
        { text: 'J’ai des émotions et j’ai besoin de les gérer', nextCardId: '1-1' },
        { text: 'Je procrastine et je veux arrêter', nextCardId: '1-12' },
        { text: 'J’ai mal', nextCardId: '5-1' },
        { text: 'Je veux dormir', nextCardId: '5-12' },
        { text: 'Je veux nettoyer', nextCardId: '4-2' },
        { text: 'Je veux manger', nextCardId: '4-7' },
      ],
    },
    {
      id: '0-3',
      title: 'Comment vous sentez-vous ?',
      items: [
        { text: 'Surexcité(e)', nextCardId: '1-6' },
        { text: 'Douleur', nextCardId: '5-1' },
        { text: 'Anxieux/Anxieuse', nextCardId: '1-2' },
        { text: 'Fatigué(e)', nextCardId: '5-11' },
        { text: 'Auto-critique / honte', nextCardId: '1-3' },
        { text: 'En colère', nextCardId: '1-4' },
        { text: 'Faim', nextCardId: '4-7' },
        { text: 'Agité(e)', nextCardId: '3-1' },
        { text: 'Ennuyé(e)', nextCardId: '2-1' },
        { text: 'Procrastination', nextCardId: '1-12' },
        { text: 'Inutile', nextCardId: '4-1' },
        { text: 'Dissocié(e) / Pas vraiment là', nextCardId: '1-6' },
      ],
    },
    {
      id: '1-1',
      title: 'J’ai des émotions et j’ai besoin de les gérer :',
      items: [
        { text: 'Panique / anxiété', nextCardId: '1-2' },
        { text: 'Honte / auto-critique', nextCardId: '1-3' },
        { text: 'Colère', nextCardId: '1-4' },
        { text: 'Sous-stimulé(e) / déprimé(e)', nextCardId: '1-14' },
        { text: 'Toutes les émotions : exercice de mise à la terre', nextCardId: '1-6' },
      ],
    },
    {
      id: '1-2',
      title: 'Gérer une crise de panique / anxiété',
      items: [
        {
          text: 'Prenez un xanax, ativan, benadryl ou autre médicament contre la panique selon les instructions',
        },
        { text: 'Écoutez de la musique' },
        { text: 'Buvez un grand verre d’eau' },
        { text: 'Exercices rapides', nextCardId: '3-2' },
        { text: 'Exercices de mise à la terre', nextCardId: '1-6' },
        { text: 'Regardez quelque chose de réconfortant', nextCardId: '2-3' },
        { text: 'Faites quelque chose de créatif', nextCardId: '2-4' },
        { text: 'Nettoyez quelque chose', nextCardId: '4-2' },
        { text: 'Mangez quelque chose', nextCardId: '4-7' },
        { text: 'Prenez une douche ou un bain' },
        { text: 'Appelez une ligne d’aide', nextCardId: '1-13' },
      ],
    },
    {
      id: '1-3',
      title: 'Gérer la honte / l’auto-critique',
      items: [
        { text: 'Faites une liste de vos choses préférées' },
        { text: 'Pensez à un moment où vous avez réussi' },
        { text: 'Listez 18 choses pour lesquelles vous êtes reconnaissant(e)' },
        { text: 'Contactez une personne de confiance' },
        { text: 'Faites un exercice de mise à la terre', nextCardId: '1-6' },
        { text: 'Gérez une crise de panique', nextCardId: '1-2' },
        { text: 'Arrêtez de procrastiner quelque chose', nextCardId: '1-12' },
      ],
    },
    {
      id: '1-4',
      title: 'Gérer la colère',
      items: [
        {
          text: 'Éloignez-vous de la situation actuelle et vérifiez comment vous vous sentez. Êtes-vous anxieux(se) ? En danger ? En mode combat-fuite ?',
        },
        { text: 'Buvez un verre d’eau' },
        { text: 'Mangez quelque chose', nextCardId: '4-7' },
        {
          text: 'Concentrez-vous sur votre respiration - inspirez sur 4 temps et expirez sur 8 temps. Répétez 10 fois.',
        },
        { text: 'Faites un exercice de mise à la terre', nextCardId: '1-6' },
        { text: 'Faites un exercice rapide', nextCardId: '3-2' },
        { text: 'Gérez une crise de panique', nextCardId: '1-2' },
      ],
    },
    {
      id: '1-5',
      title: 'Solutions pour la surexcitation',
      items: [
        { text: 'Écoutez de la musique' },
        { text: 'Bouchons d’oreille' },
        { text: 'Casque antibruit' },
        { text: 'Bruit blanc' },
        { text: 'Prenez une douche' },
        { text: 'Coiffez vos cheveux' },
        { text: 'Tenez-vous au milieu d’une pièce calme et respirez' },
        { text: 'Enlevez le vêtement qui vous gêne' },
        { text: 'Pastille pour la toux' },
        { text: 'Faites du cardio', nextCardId: '3-3' },
        { text: 'Faites du yoga', nextCardId: '3-4' },
        { text: 'Mangez quelque chose', nextCardId: '4-7' },
        { text: 'Exercice de mise à la terre', nextCardId: '1-6' },
        { text: 'Dormez', nextCardId: '5-12' },
      ],
    },
    {
      id: '1-6',
      title: 'Techniques de mise à la terre',
      items: [
        { text: 'Techniques de mise à la terre mentale', nextCardId: '1-7' },
        { text: 'Techniques de mise à la terre physique', nextCardId: '1-10' },
        { text: 'Techniques de mise à la terre apaisantes', nextCardId: '1-11' },
        { text: 'Exercice de mise à la terre "5-4-3-2-1"', nextCardId: '1-8' },
        { text: 'Exercice de l’avion', nextCardId: '1-9' },
      ],
    },
    {
      id: '1-7',
      title: 'Techniques de mise à la terre mentale',
      items: [
        { text: 'Décrivez votre environnement à voix haute en détail, en utilisant tous vos sens' },
        { text: 'Listez tous les éléments d’une catégorie (par exemple, les noms de chaque arbre)' },
        { text: 'Décrivez une activité quotidienne en détail (par exemple, comment faire du café)' },
        { text: 'Lisez quelque chose à voix haute' },
        { text: 'Pensez à un mot et épellez-le à l’envers' },
        { text: 'Comptez jusqu’à 10 à voix haute' },
        { text: 'Dites l’alphabet très lentement' },
        { text: 'Répétez une citation préférée' },
        { text: 'Trouvez quelque chose que vous pouvez voir pour chaque couleur de l’arc-en-ciel' },
        { text: 'Exercice "5-4-3-2-1"', nextCardId: '1-8' },
        { text: 'Faites la technique de l’avion', nextCardId: '1-9' },
      ],
    },
    {
      id: '1-8',
      title: 'Exercice de mise à la terre "5-4-3-2-1"',
      items: [
        { text: '5 choses que vous pouvez voir' },
        { text: '4 choses que vous pouvez toucher ou sentir' },
        { text: '3 choses que vous pouvez entendre' },
        { text: '2 choses que vous pouvez sentir' },
        { text: '1 chose que vous pouvez goûter' },
      ],
    },
    {
      id: '1-9',
      title: 'Exercice de l’avion pour la panique',
      items: [
        {
          text: 'Imaginez un avion. C’est votre avion et seulement le vôtre. Vous décidez ce que vous voulez en faire. Pour chaque question suivante, répondez à voix haute.',
        },
        { text: 'De quelle couleur sera l’extérieur ?' },
        { text: 'Et l’intérieur ?' },
        { text: 'Et les sièges ? Sont-ils moelleux ou normaux ? Et de quelle couleur ?' },
        { text: 'Maintenant, 3 plats à servir. Une entrée, un plat principal et un dessert' },
        {
          text: 'Qui voulez-vous emmener dans l’avion ? Cela peut être jusqu’à 24 personnes, réelles ou fictives',
        },
        { text: 'Y a-t-il des décorations dans l’avion ?' },
        { text: 'À quoi ressembleraient les hôtesses de l’air ?' },
        { text: 'Où va l’avion ?' },
      ],
    },
    {
      id: '1-10',
      title: 'Techniques de mise à la terre physique',
      items: [
        { text: 'Éclaboussez vos mains et votre visage avec de l’eau fraîche' },
        { text: 'Saisissez quelque chose aussi fort que possible, puis relâchez. Répétez.' },
        { text: 'Touchez des objets autour de vous et remarquez les détails sensoriels' },
        { text: 'Enfoncez vos talons dans le sol' },
        { text: 'Sautez sur place' },
        { text: 'Remarquez votre corps, ce que chaque muscle fait' },
        { text: 'Étirez-vous' },
        { text: 'Marchez lentement en remarquant chaque pas' },
        { text: 'Mangez quelque chose et décrivez ses saveurs' },
        { text: 'Concentrez-vous sur votre respiration - inspirez sur 4 temps et expirez sur 8 temps.' },
      ],
    },
    {
      id: '1-11',
      title: 'Techniques de mise à la terre apaisantes',
      items: [
        { text: 'Dites des affirmations bienveillantes' },
        { text: 'Pensez à vos choses préférées, aliments, personnes, animaux' },
        { text: 'Visualisez des personnes que vous aimez' },
        { text: 'Rappelez-vous les paroles d’une chanson, citation ou poème inspirant' },
        { text: 'Rappelez-vous un endroit sûr' },
        { text: 'Dites une affirmation de coping' },
        { text: 'Planifiez une petite récompense pour vous-même' },
        { text: 'Pensez à des choses que vous attendez avec impatience dans la semaine à venir' },
      ],
    },
    {
      id: '1-12',
      title: 'Je procrastine et je veux arrêter',
      items: [
        { text: 'Divisez la tâche en sous-tâches jusqu’à ce que chaque tâche semble moins écrasante' },
        { text: 'Trouvez un moyen de commencer (même en faisant un petit progrès)' },
        { text: 'Rendez-la plus intéressante' },
        {
          text: 'Arrêtez et essayez de comprendre s’il y a un blocage mental (par exemple, vous ne comprenez pas la tâche, vous avez une mauvaise association avec elle ou vous êtes coincé(e) sur quelque chose de spécifique)',
        },
      ],
    },
    {
      id: '1-13',
      title: 'Lignes d’aide pour plus de soutien',
      items: [
        { text: 'Australie et Nouvelle-Zélande :' },
        { text: 'Lifeline Australie : 13 11 14' },
        { text: 'Lifeline Nouvelle-Zélande : 09 5222 999 (Auckland), 0800 543 354 (Reste de la NZ)' },
        { text: 'Canada :' },
        { text: 'Services de crise Canada : 1-833-456-4566 (gratuit)' },
        { text: 'Au Québec : 1-866-277-3553' },
        { text: 'France (anglophone) :' },
        { text: 'Suicide Écoute : 0033 145 39 4000' },
        { text: 'SOS Help : 01 46 21 46 46' },
        { text: 'Allemagne :' },
        { text: 'Telefonseelsorge Deutschland (National) :' },
        { text: 'En allemand : 0800 -111 0 222' },
        { text: 'En anglais : 030-44 01 06 07' },
        { text: 'Italie :' },
        { text: 'Samaritans : 800 86 00 22' },
        { text: 'Japon :' },
        { text: 'Befrienders International, Tokyo : +81 (0) 3 5286 9090' },
        { text: 'BI Suicide Prevention Centre, Osaka : +81 (0) 6 4395 4343' },
        { text: 'Tokyo English Lifeline : 107-0062' },
        { text: 'Afrique du Sud :' },
        { text: 'Lifeline Afrique du Sud : 0861 322 322' },
        { text: 'Royaume-Uni et République d’Irlande :' },
        { text: 'Samaritans : 116 123' },
        { text: 'HopeLine UK : 0800 068 4141' },
        { text: 'Ireland Lifeline : 0808 808 8000' },
        { text: 'États-Unis :' },
        { text: 'Ligne de crise et de suicide - appelez ou envoyez un SMS au 988' },
        { text: 'The Trevor Project : 866-488-7386' },
        { text: 'Trans Lifeline : 877-565-8860' },
        { text: 'HopeLine : 1-800-273-TALK (8255)' },
        { text: 'Plus de lignes d’aide internationales disponibles sur suicide.org' },
      ],
    },
    {
      id: '1-14',
      title: 'Solutions pour la sous-stimulation',
      items: [
        { text: 'Activité physique', nextCardId: '3-1' },
        { text: 'Lumière du soleil', nextCardId: '2-7' },
        { text: 'Nourriture', nextCardId: '4-7' },
        { text: 'Sommeil', nextCardId: '5-12' },
        { text: 'Temps personnel', nextCardId: '2-1' },
        { text: 'Expression créative', nextCardId: '2-4' },
      ],
    },
    {
      id: '2-1',
      title: 'Je m’ennuie et je veux faire quelque chose :',
      items: [
        { text: 'Bougez mon corps', nextCardId: '3-1' },
        { text: 'Lisez quelque chose', nextCardId: '2-2' },
        { text: 'Regardez quelque chose', nextCardId: '2-3' },
        { text: 'Soyez créatif(ve)', nextCardId: '2-4' },
        { text: 'Apprenez quelque chose', nextCardId: '2-5' },
        { text: 'Faites quelque chose d’utile', nextCardId: '4-1' },
        { text: 'Partez à l’aventure', nextCardId: '2-7' },
        { text: 'Jouez à un jeu', nextCardId: '2-8' },
      ],
    },
    {
      id: '2-2',
      title: 'Que voulez-vous lire ?',
      items: [
        { text: 'Fiction' },
        { text: 'Poésie' },
        { text: 'Non-fiction' },
        { text: 'Fiction pour jeunes adultes' },
        { text: 'Science-fiction' },
        { text: 'Fantasy' },
        { text: 'Mystère' },
        { text: 'Horreur' },
        { text: 'Romance' },
        { text: 'Allez sur Project Gutenberg pour des ebooks gratuits et légaux' },
        {
          text: 'Connectez votre carte de bibliothèque à Libby pour des ebooks gratuits et à Overdrive pour des audiobooks gratuits',
        },
        { text: 'Fanfiction', link: 'http://archiveofourown.org' },
      ],
    },
    {
      id: '2-3',
      title: 'Que voulez-vous regarder ?',
      items: [
        { text: 'Film réconfortant' },
        { text: 'Nouveau film' },
        { text: 'Série réconfortante' },
        { text: 'Nouvelle série' },
        { text: 'Documentaire' },
      ],
    },
    {
      id: '2-4',
      title: 'Choses créatives à faire',
      items: [
        { text: 'Coudre / Faire du patchwork' },
        { text: 'Crocheter / Tricoter' },
        { text: 'Tisser' },
        { text: 'Dessiner' },
        { text: 'Peindre' },
        { text: 'Calligraphie' },
        { text: 'Écrire de la fiction' },
        { text: 'Écrire de la poésie' },
        { text: 'Origami' },
        { text: 'Broder' },
        { text: 'Construire quelque chose' },
      ],
    },
    {
      id: '2-5',
      title: 'Moyens d’apprendre des choses :',
      items: [
        { text: 'Apprenez une langue', nextCardId: '2-6' },
        { text: 'Wikipedia', link: 'https://en.wikipedia.org' },
        { text: 'TedX Talks', link: 'https://www.ted.com/watch/tedx-talks' },
        { text: 'Explorez l’océan avec nautiluslive.org', link: 'http://nautiluslive.org' },
        { text: 'Choisissez le premier cours intéressant que vous voyez sur EdX' },
        { text: 'Regardez un documentaire PBS' },
        { text: 'Commencez à lire le premier livre de non-fiction non lu sur votre étagère' },
        {
          text: 'Lisez un article aléatoire sur Wikipedia',
          link: 'https://en.wikipedia.org/wiki/Special:Random',
        },
      ],
    },
    {
      id: '2-6',
      title: 'Apprenez une langue',
      items: [
        { text: 'Drops', link: 'https://languagedrops.com/' },
        {
          text: 'Mango Languages (gratuit avec une carte de bibliothèque)',
          link: 'https://mangolanguages.com/',
        },
        { text: 'Duolingo', link: 'https://www.duolingo.com/' },
      ],
    },
    {
      id: '2-7',
      title: 'Partez à l’aventure',
      items: [
        { text: 'Randonnée' },
        { text: 'Observation des oiseaux' },
        { text: 'Vélo' },
        { text: 'Parc d’État / zone naturelle' },
        { text: 'Musée' },
        { text: 'Jardin botanique' },
        { text: 'Verger' },
        { text: 'Musée des sciences' },
        { text: 'Librairie' },
        { text: 'Magasin d’artisanat' },
        { text: 'Nouveau restaurant' },
        { text: 'Zoo' },
        { text: 'Aquarium' },
      ],
    },
    {
      id: '2-8',
      title: 'Jouez à un jeu',
      items: [
        { text: 'Jeux de cartes' },
        { text: 'Jeux de société' },
        { text: 'Jeux vidéo' },
        { text: 'Jeux sur téléphone' },
      ],
    },
    {
      id: '3-1',
      title: 'Quel type d’exercice voulez-vous faire ?',
      items: [
        { text: 'Exercices de poids corporel sans besoin de salle de sport', nextCardId: '3-2' },
        { text: 'Yoga', nextCardId: '3-4' },
        { text: 'Cardio sans besoin de salle de sport', nextCardId: '3-3' },
      ],
    },
    {
      id: '3-2',
      title: 'Exercices de poids corporel',
      items: [
        { text: 'Pompes contre le mur' },
        { text: 'Dips sur chaise' },
        { text: 'Squats' },
        { text: 'Fentes' },
        { text: 'Élévations des mollets' },
        { text: 'Abdominaux' },
      ],
    },
    {
      id: '3-3',
      title: 'Exercices de cardio',
      items: [
        { text: 'Marche rapide' },
        { text: 'Course à pied' },
        { text: 'Elliptique' },
        { text: 'Tapis de course' },
        { text: 'Vélo' },
        { text: 'Sauts avec écart' },
        { text: 'Burpees' },
        { text: 'Corde à sauter' },
        { text: 'Danse' },
      ],
    },
    {
      id: '3-4',
      title: 'Ressources pour le yoga',
      items: [
        { text: 'Chaîne YouTube Yoga with Adriene', link: 'https://www.youtube.com/user/yogawithadriene' },
        { text: 'Jessamyn à The Underbelly', link: 'https://theunderbelly.com/' },
        { text: 'James Knight à Gentle Somatic Yoga', link: 'https://www.gentlesomaticyoga.com/' },
        { text: 'Dianne Bondy à Yoga for Every Body', link: 'https://diannebondyyoga.com/' },
        { text: 'Val Verdier', link: 'https://www.instagram.com/valerie.a.verdier/?hl=en' },
      ],
    },
    {
      id: '4-1',
      title: 'Choses utiles à faire',
      items: [
        { text: 'Nettoyez quelque chose', nextCardId: '4-2' },
        { text: 'Faites vos devoirs' },
        { text: 'Vérifiez votre compte bancaire / finances' },
        { text: 'Cuisinez un repas' },
        { text: 'Organisez un placard, une étagère, un dressing ou un autre espace discret' },
        { text: 'Appelez un ami ou un proche pour prendre de ses nouvelles' },
        { text: 'Triez le courrier' },
        { text: 'Sortez les poubelles / le recyclage' },
      ],
    },
    {
      id: '4-2',
      title: 'Choses à nettoyer',
      items: [
        { text: 'Cuisine', nextCardId: '4-3' },
        { text: 'Salle de bain', nextCardId: '4-4' },
        { text: 'Chambre', nextCardId: '4-5' },
        { text: 'Espace de vie général', nextCardId: '4-6' },
      ],
    },
    {
      id: '4-3',
      title: 'Nettoyer la cuisine',
      items: [
        { text: 'Rangez la vaisselle propre' },
        { text: 'Lavez la vaisselle sale' },
        { text: 'Nettoyez les comptoirs et la cuisinière' },
        { text: 'Balayez le sol de la cuisine' },
        { text: 'Nettoyez les étagères du frigo' },
        { text: 'Jetez les aliments périmés' },
        { text: 'Videz la poubelle' },
        { text: 'Organisez le frigo et le garde-manger' },
      ],
    },
    {
      id: '4-4',
      title: 'Nettoyer la salle de bain',
      items: [
        { text: 'Désinfectez les toilettes avec une brosse et un nettoyant pour toilettes' },
        { text: 'Videz la poubelle' },
        { text: 'Nettoyez le miroir, les comptoirs et le sol' },
        { text: 'Lavez le rideau de douche' },
        { text: 'Frottez la moisissure dans la baignoire / douche' },
        { text: 'Mettez le linge sale / les serviettes dans le panier à linge' },
        { text: 'Organisez le comptoir / l’armoire' },
        { text: 'Balayez / aspirez le sol' },
      ],
    },
    {
      id: '4-5',
      title: 'Nettoyer la chambre',
      items: [
        { text: 'Changez les draps du lit' },
        { text: 'Mettez les draps sales dans la machine à laver' },
        { text: 'Mettez le linge sale dans le panier à linge' },
        { text: 'Videz la poubelle' },
        { text: 'Pliez le linge propre' },
        { text: 'Rangez le linge propre' },
        { text: 'Balayez / aspirez le sol' },
        { text: 'Nettoyez le dessus des meubles' },
        { text: 'Organisez la table de chevet / la commode' },
      ],
    },
    {
      id: '4-6',
      title: 'Nettoyer l’espace de vie général',
      items: [
        { text: 'Aspirez tous les tapis ou moquettes visibles' },
        { text: 'Balayez ou aspirez les sols' },
        { text: 'Rangez le désordre et rangez les objets' },
        { text: 'Faites le tour avec un sac poubelle et jetez tous les déchets' },
      ],
    },
    {
      id: '4-7',
      title: 'Vous avez besoin de manger. Où êtes-vous ?',
      items: [
        { text: 'À la maison', nextCardId: '4-8' },
        { text: 'Au travail', nextCardId: '4-9' },
        { text: 'Au supermarché', nextCardId: '4-10' },
        { text: 'Ailleurs', nextCardId: '4-11' },
      ],
    },
    {
      id: '4-8',
      title: 'Vous voulez manger quelque chose et vous êtes à la maison.',
      items: [
        { text: 'Une cuillère de beurre de cacahuète' },
        { text: 'Une tranche de pain avec de la confiture ou du beurre' },
        { text: 'Un œuf brouillé' },
        { text: 'Flocons d’avoine' },
        { text: 'Céréales' },
        { text: 'Crackers' },
        { text: 'Fromage' },
        { text: 'Lait au chocolat' },
        { text: 'Légumes crus (carottes, brocoli, concombre) avec du houmous ou de la vinaigrette' },
        {
          text: 'Faites chauffer au micro-ondes un bol de légumes surgelés avec de l’huile d’olive, du sel, du poivre et d’autres épices (paprika ! cumin ! thym !)',
        },
        { text: 'Fruit' },
        { text: 'Cacahuètes, noix, autres noix ou graines' },
        { text: 'Un verre de jus / smoothie' },
        { text: 'Aliments emballés (par exemple, pop-tarts, burritos micro-ondes)' },
        { text: 'Aliments faciles à digérer : Banane, Riz, Compote de pommes, Toast, Yaourt' },
      ],
    },
    {
      id: '4-9',
      title: 'Vous avez faim et vous êtes au travail.',
      items: [
        { text: 'Hoummous et crackers' },
        { text: 'Yaourt' },
        { text: 'Bâtonnet de fromage' },
        { text: 'Bagel / muffin anglais / toast' },
        { text: 'Bar à salade : légumes verts, graines, noix, fruits, œufs durs' },
        { text: 'Bar à soupe' },
        { text: 'Barre granola' },
        { text: 'M&Ms cacahuètes' },
        { text: 'Mélange de fruits secs' },
        {
          text: 'Tout ce qui contient des protéines / graisses / fibres vous rassasiera plus longtemps que quelque chose avec juste du sucre / de la farine.',
        },
        {
          text: 'Commandez une livraison via DoorDash, Panera Bread, une pizzeria locale, etc. (si disponible).',
        },
        { text: 'Vérifiez les salles de pause pour de la nourriture gratuite' },
        { text: 'Demandez à vos collègues' },
      ],
    },
    {
      id: '4-10',
      title: 'Vous avez faim et vous êtes au supermarché.',
      items: [
        { text: 'Repas préparés dans la section des aliments frais' },
        { text: 'Fruits / légumes crus pré-lavés et emballés (section des produits frais)' },
        { text: 'Lunchable (section traiteur)' },
        { text: 'Fromage emballé individuellement (rayon des produits laitiers)' },
        { text: 'Yaourt (rayon des produits laitiers)' },
        {
          text: 'Poches de nourriture pour bébé (disponibles dans le rayon bébé, pas besoin d’ustensiles, variétés incluent Banane & Citrouille, Mangue & Kale, Fraise Banane.)',
        },
        { text: 'Smoothie préparé (rayon des boissons)' },
      ],
    },
    {
      id: '4-11',
      title: 'Vous avez faim et vous êtes dehors.',
      items: [
        { text: 'Station-service (smoothie préparé, biscuits, noix, pâtisseries emballées)' },
        {
          text: 'Fast-food (Vous n’êtes pas obligé(e) de commander un repas complet à 8 $. Vous pouvez prendre juste des frites, un milkshake ou un paquet de 4 nuggets de poulet)',
        },
        { text: 'Supermarché', nextCardId: '4-10' },
        { text: 'À la maison', nextCardId: '4-8' },
      ],
    },
    {
      id: '5-1',
      title: 'Quel type de douleur avez-vous ?',
      items: [
        { text: 'Douleur menstruelle / pelvienne', nextCardId: '5-2' },
        { text: 'Douleur articulaire', nextCardId: '5-3' },
        { text: 'Tête', nextCardId: '5-5' },
        { text: 'Douleur musculaire due à l’exercice', nextCardId: '5-4' },
        { text: 'Estomac', nextCardId: '5-10' },
      ],
    },
    {
      id: '5-2',
      title: 'Comment gérer la douleur menstruelle',
      items: [
        { text: 'Appliquez une bouillotte' },
        {
          text: 'Prenez un anti-inflammatoire non stéroïdien (AINS) (par exemple, ibuprofène, Motrin, Advil, Aleve). Prenez avec un grand verre d’eau pour éviter les brûlures d’estomac. Ne buvez pas d’alcool en prenant des AINS.',
        },
        { text: 'Unité TENS' },
        { text: 'Exercice', nextCardId: '3-1' },
        { text: 'Buvez de l’eau' },
        { text: 'Prenez un bain chaud' },
        { text: 'Mangez du chocolat' },
        { text: 'Mangez quelque chose de salé' },
        { text: 'Distrayez-vous', nextCardId: '2-1' },
      ],
    },
    {
      id: '5-3',
      title: 'Comment gérer la douleur articulaire / due à une blessure',
      items: [
        {
          text: 'Prenez un anti-inflammatoire non stéroïdien (AINS) (par exemple, ibuprofène, Motrin, Advil, Aleve). Prenez avec un grand verre d’eau pour éviter les brûlures d’estomac. Ne buvez pas d’alcool en prenant des AINS.',
        },
        {
          text: 'Appliquez de la glace ou de la chaleur (selon ce qui vous fait du bien) pendant 20 minutes, puis reposez-vous pendant 20 minutes, répétez.',
        },
        { text: 'Massage' },
        { text: 'Rouleau en mousse' },
        { text: 'Bain chaud' },
        { text: 'Choisissez une vidéo de yoga axée sur cette zone', nextCardId: '3-4' },
      ],
    },
    {
      id: '5-4',
      title: 'Comment gérer les courbatures',
      items: [
        {
          text: 'Prenez un anti-inflammatoire non stéroïdien (AINS) (par exemple, ibuprofène, Motrin, Advil, Aleve). Prenez avec un grand verre d’eau pour éviter les brûlures d’estomac. Ne buvez pas d’alcool en prenant des AINS.',
        },
        { text: 'Buvez de l’eau' },
        { text: 'Étirements' },
        { text: 'Yoga', nextCardId: '3-4' },
        { text: 'Cardio léger', nextCardId: '3-3' },
        { text: 'Bain chaud' },
      ],
    },
    {
      id: '5-5',
      title: 'Quel type de douleur à la tête ?',
      items: [
        { text: 'Sinus (quand j’appuie sur mon visage, ça fait plus mal)', nextCardId: '5-6' },
        {
          text: 'Tension (les épaules et le cou font mal, ou un élastique serre mon crâne)',
          nextCardId: '5-7',
        },
        {
          text: 'Migraine (sensibilité à la lumière/au bruit/aux odeurs, nausées, brouillard mental, émotions désordonnées)',
          nextCardId: '5-8',
        },
        { text: 'Mal de tête général', nextCardId: '5-9' },
      ],
    },
    {
      id: '5-6',
      title: 'Comment gérer un mal de tête des sinus',
      items: [
        {
          text: 'Prenez un anti-inflammatoire non stéroïdien (AINS) (par exemple, ibuprofène, Motrin, Advil, Aleve). Prenez avec un grand verre d’eau pour éviter les brûlures d’estomac. Ne buvez pas d’alcool en prenant des AINS.',
        },
        { text: 'Prenez un décongestionnant (Sudafed, Mucinex, etc.)' },
        { text: 'Spray nasal salin' },
        { text: 'Douche' },
        { text: 'Buvez de l’eau' },
        { text: 'Poche de glace (enveloppée dans une serviette) sur votre visage' },
        {
          text: 'Enveloppez votre visage dans une serviette et massez votre visage avec un vibreur sur la vitesse la plus basse',
        },
      ],
    },
    {
      id: '5-7',
      title: 'Comment gérer un mal de tête de tension',
      items: [
        { text: 'Massage du cou/dos' },
        { text: 'Bouillotte ou poche de glace (selon ce qui vous fait du bien)' },
        {
          text: 'Prenez un anti-inflammatoire non stéroïdien (AINS) (par exemple, ibuprofène, Motrin, Advil, Aleve). Prenez avec un grand verre d’eau pour éviter les brûlures d’estomac. Ne buvez pas d’alcool en prenant des AINS.',
        },
        { text: 'Relaxant musculaire (si prescrit)' },
        { text: 'Prenez une douche chaude' },
        { text: 'Cardio', nextCardId: '3-3' },
        { text: 'Desserrez votre mâchoire' },
        { text: 'Exercice léger', nextCardId: '3-1' },
      ],
    },
    {
      id: '5-8',
      title: 'Comment gérer une migraine (avec aura)',
      items: [
        { text: 'Prenez vos médicaments d’urgence contre la migraine (si prescrits)' },
        { text: 'Buvez un grand verre d’eau' },
        {
          text: 'Prenez un anti-inflammatoire non stéroïdien (AINS) (par exemple, ibuprofène, Motrin, Advil, Aleve). Prenez avec un grand verre d’eau pour éviter les brûlures d’estomac. Ne buvez pas d’alcool en prenant des AINS ou d’autres médicaments contre la migraine.',
        },
        { text: 'Prenez 1 000 mg d’oxyde de magnésium' },
        { text: 'Prenez un benadryl et faites une sieste' },
        { text: 'Mangez quelque chose', nextCardId: '4-7' },
        {
          text: 'Mettez une poche de glace ou une bouillotte sur votre tête, selon ce qui vous fait du bien',
        },
        { text: 'Allongez-vous dans une pièce sombre et calme' },
        { text: 'Mettez des bouchons d’oreille' },
        { text: 'Dormez', nextCardId: '5-12' },
        { text: 'Évitez les lumières vives / les appareils à lumière bleue' },
      ],
    },
    {
      id: '5-9',
      title: 'Comment gérer un mal de tête général',
      items: [
        {
          text: 'Prenez un anti-inflammatoire non stéroïdien (AINS) (par exemple, ibuprofène, Motrin, Advil, Aleve). Prenez avec un grand verre d’eau pour éviter les brûlures d’estomac. Ne buvez pas d’alcool en prenant des AINS.',
        },
        { text: 'Mangez quelque chose', nextCardId: '4-7' },
        { text: 'Buvez un grand verre d’eau' },
        { text: 'Reposez-vous si cela vous fait du bien' },
        { text: 'Exercice léger si cela vous fait du bien' },
        { text: 'Réduisez les stimuli - sons, lumières, téléphone, humains' },
      ],
    },
    {
      id: '5-10',
      title: 'Douleur à l’estomac ou nausées',
      items: [
        { text: 'Tums - si vous avez des brûlures d’estomac, des maux d’estomac ou une indigestion' },
        { text: 'Gas-X - si vous vous sentez gazeux / ballonné' },
        { text: 'Buvez un verre d’eau' },
        { text: 'Toast/crackers/banane mangés en petites bouchées' },
        { text: 'Ginger ale ou thé au gingembre' },
        {
          text: 'Si vous avez des nausées, allongez-vous sur votre côté gauche (si confortable). Cela place votre estomac sous votre œsophage et peut réduire les nausées / l’envie de vomir.',
        },
      ],
    },
    {
      id: '5-11',
      title: 'Quand vous avez mal dormi',
      items: [
        { text: 'Faites une sieste' },
        {
          text: 'Fermez les yeux, détendez votre corps et concentrez-vous sur votre respiration pendant 3-5 minutes',
        },
        { text: 'Buvez de l’eau' },
        { text: 'Prenez un bain chaud' },
        { text: 'Prévenez la surexcitation', nextCardId: '1-5' },
        { text: 'Prévenez une migraine', nextCardId: '5-5' },
        { text: 'Faites un exercice de mise à la terre', nextCardId: '1-6' },
      ],
    },
    {
      id: '5-12',
      title: 'Améliorer l’hygiène du sommeil',
      items: [
        { text: 'J’ai mal dormi la nuit dernière', nextCardId: '5-11' },
        { text: 'J’ai de l’insomnie MAINTENANT', nextCardId: '5-15' },
        { text: 'Améliorer le sommeil en général', nextCardId: '5-13' },
        { text: 'Je dois parler à un médecin de mes problèmes de sommeil', nextCardId: '5-14' },
      ],
    },
    {
      id: '5-13',
      title: 'Conseils pour améliorer l’hygiène du sommeil',
      items: [
        {
          text: 'Réglez une alarme pour commencer votre routine nocturne à la même heure chaque soir, même si vous n’êtes pas fatigué(e) quand l’alarme sonne. L’objectif est de terminer toutes les tâches du coucher. Ensuite, la seule tâche restante est de fermer les yeux.',
        },
        {
          text: 'Essayez de faire suffisamment d’activité physique pendant la journée. Cela peut réduire l’agitation que vous ressentez lorsque vous vous allongez enfin.',
        },
        {
          text: 'Déterminez jusqu’à quelle heure vous pouvez consommer de la caféine sans qu’elle affecte votre coucher, et respectez cette règle autant que possible. Savoir comment la caféine vous affecte peut vous aider à contrôler son impact.',
        },
        {
          text: 'Déterminez jusqu’à quelle heure vous pouvez prendre vos médicaments pour le TDAH ou d’autres stimulants sans qu’ils affectent votre coucher. Vous devrez peut-être régler une alarme pour prendre vos médicaments du matin assez tôt.',
        },
        { text: 'Installez un filtre de lumière bleue pour votre téléphone / ordinateur' },
        { text: 'Parlez à votre médecin de vos problèmes de sommeil', nextCardId: '5-14' },
      ],
    },
    {
      id: '5-14',
      title: 'Problèmes de sommeil à discuter avec votre médecin',
      items: [
        {
          text: 'Ronflez-vous ? Ou respirez-vous bruyamment la nuit ? Parlez à votre médecin d’un test de sommeil pour l’apnée obstructive du sommeil. De nombreux tests d’apnée peuvent être effectués à domicile pendant la nuit.',
        },
        {
          text: 'Vous endormez-vous à des moments / endroits aléatoires ? Beaucoup de personnes atteintes de TDAH ont également de la narcolepsie ou un autre trouble du sommeil. Parlez de vos symptômes à votre médecin.',
        },
        { text: 'Avez-vous des migraines ?' },
        {
          text: 'Est-il difficile de s’endormir parce que vos pensées commencent à tourner et que votre anxiété augmente ? Vous pourriez bénéficier d’un médicament anti-anxiété pris au coucher pour arrêter les pensées qui tournent.',
        },
      ],
    },
    {
      id: '5-15',
      title: 'Gérer l’insomnie',
      items: [
        { text: 'Éteignez les lumières vives' },
        { text: 'Utilisez le mode sombre et le filtre de lumière bleue sur vos appareils' },
        {
          text: 'Ne regardez pas de vidéos / films / émissions excitants ou mentalement intenses juste avant de dormir',
        },
        { text: 'Prenez une collation avant de dormir' },
        { text: 'Prenez de la mélatonine ou du benadryl avant de dormir' },
        { text: 'Prenez une douche chaude. Votre corps se sentira plus somnolent en refroidissant.' },
        {
          text: 'Essayez une application de méditation (comme l’application gratuite et sans publicité Mindfulness Coach du Département des Anciens Combattants des États-Unis)',
        },
        { text: 'Écoutez de la musique relaxante, des livres audio ou des podcasts.' },
        {
          text: 'Si les bruits nocturnes vous dérangent, essayez des bouchons d’oreille. Assurez-vous que votre réveil est réglé sur le volume le plus fort et sur la vibration.',
        },
        {
          text: 'Posez le téléphone. Fermez les yeux. Respirez régulièrement et travaillez à détendre tous vos muscles, en commençant par votre tête et en descendant lentement.',
        },
        {
          text: 'Rappelez-vous que même si vous ne pouvez pas dormir, simplement vous allonger avec les yeux fermés donnera à votre esprit et à votre corps un peu de repos.',
        },
      ],
    },
  ],
};

// The first one will be the default set
export const availableSets: ICardSet[] = [analogBrainCards, analogBrainCardsFrench];
